### ISSUE TITLE
The NAPT patches should not change default lwip/opt.h settings (IDFGH-3150)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-lwip#16]
Hi @david-cermak 

The NAPT patches changed the src/include/lwip/opt.h which may cause problem for existing users.
IMHO, new settings should be disabled by default.

**Comment by david-cermak** [comment]
Hi @AxelLin 

Yes, I agree that the NAPT should be disabled by default and I believe they are.
Please check the changes against `2.1.2-esp` branch, especially the NAPT related commits:
https://github.com/espressif/esp-lwip/compare/5c181728c894d8c051070b1cf21c55a6222fc64b...754b8d5dcb2a2626d81918b60772c18dee41e54e
(updates in `src/include/lwip/opt.h` been reverted)

**Comment by AxelLin** [comment]
Got it.
Thanks.
