### ISSUE TITLE
build error, like .h file not include? (IDFGH-3661)

### ISSUE THREAD

**Issue by betashepherd** [espressif/esp-lwip#17]
from /opt/Espressif/esp-idf/components/esp_event/default_event_loop.c:15:
/opt/Espressif/esp-idf/components/lwip/lwip/src/include/lwip/ip.h:78:3: error: unknown type name 'ip_addr_t'
   ip_addr_t local_ip; \
   ^
/opt/Espressif/esp-idf/components/lwip/lwip/src/include/lwip/ip.h:91:3: note: in expansion of macro 'IP_PCB'
   IP_PCB;
   ^
/opt/Espressif/esp-idf/components/lwip/lwip/src/include/lwip/ip.h:79:3: error: unknown type name 'ip_addr_t'
   ip_addr_t remote_ip; \
   ^
/opt/Espressif/esp-idf/components/lwip/lwip/src/include/lwip/ip.h:91:3: note: in expansion of macro 'IP_PCB'
   IP_PCB;

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
@betashepherd Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by david-cermak** [comment]
@betashepherd Please reopen with more details on reproducing your issue. Closing for now. If you're experiencing issues with building IDF code (`default_event_loop.c`), please prefer raising a new issue in IDF repo.
