### ISSUE TITLE
To sync with upstream lwIP-v2.1.3 release (IDFGH-6197)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-lwip#36]
lwIP 2.1.3 is now available which is a bugfix-only release.
All users are strongly suggested to upgrade!

https://savannah.nongnu.org/forum/forum.php?forum_id=10072

**Comment by david-cermak** [comment]
Thanks for posting this issue, will keep it open to track down the progress on upgrading to `2.1.3`

**Comment by AxelLin** [comment]
Please consider this as bug fix since lwIP 2.1.3 is a bugfix-only release.

BTW, it's quite misleading that esp-lwip version is 2.1.3 now. It makes people think it's already based on upstream 2.1.3.
https://github.com/espressif/esp-lwip/blob/2.1.2-esp/src/include/lwip/init.h#L53-L57

**Comment by AxelLin** [comment]
@david-cermak 
Just to confirm if this is done by 2.1.3-esp? If so, you can close this issue.
Thanks.

**Comment by david-cermak** [comment]
@AxelLin Thanks for the reminder. Yes, this could be closed.

Migration to `2.1.3` has been completed and current IDF master references [`2.1.3-esp`](https://github.com/espressif/esp-lwip/tree/2.1.3-esp).
Note this page: https://github.com/espressif/esp-lwip/wiki/Espressif-patches-in-2.1.3-esp-on-top-of-2.1.3-rel that lists all Espressif patches (on top of `STABLE 2_1_3_RELEASE`) with links to commits and upstream patches/bugs.

**Comment by AxelLin** [comment]
@david-cermak 

FYI, lwIP 2.2.0 released
https://lists.nongnu.org/archive/html/lwip-users/2023-09/msg00008.html
