### ISSUE TITLE
Does LWIP support DNS over TLS (IDFGH-6743)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-lwip#40]

**Comment by david-cermak** [comment]
Hi @shun-dgut 

You mean DNSSEC as defined in [rfc4033](https://datatracker.ietf.org/doc/html/rfc4033)? No, I'm not aware of any lwip implementation. Or did you mean some kind of carrying the DNS over (d?)tls?
The only option I could think of is to implement an external resolver and add it to lwip's DNS module using `LWIP_HOOK`s.

**Comment by shun-dgut** [comment]
> Hi @shun-dgut
> 
> You mean DNSSEC as defined in [rfc4033](https://datatracker.ietf.org/doc/html/rfc4033)? No, I'm not aware of any lwip implementation. Or did you mean some kind of carrying the DNS over (d?)tls? The only option I could think of is to implement an external resolver and add it to lwip's DNS module using `LWIP_HOOK`s.

yes, i mean DNSSEC as defined in rfc4033

**Comment by shun-dgut** [comment]
> Hi @shun-dgut
> 
> You mean DNSSEC as defined in [rfc4033](https://datatracker.ietf.org/doc/html/rfc4033)? No, I'm not aware of any lwip implementation. Or did you mean some kind of carrying the DNS over (d?)tls? The only option I could think of is to implement an external resolver and add it to lwip's DNS module using `LWIP_HOOK`s.

i means rfc7858

**Comment by david-cermak** [comment]
> i means rfc7858

Thanks. This could be perhaps a little easier to implement, but unfortunately, the same story, not supported.

**Comment by shun-dgut** [comment]
Thanks
