### ISSUE TITLE
[Bug] Is that wrong? (IDFGH-9835)

### ISSUE THREAD

**Issue by briliant-ben** [espressif/esp-lwip#54]
https://github.com/espressif/esp-lwip/blob/d5e56d06658ae11292be1baea56204f7120b6fa7/test/apps/linux/sys_arch.c#L666

**Comment by david-cermak** [comment]
It is wrong, yes!

not a *big issue* though, `sys_sem_t` is defined as:
```cpp
typedef struct sys_sem * sys_sem_t;
```
which means that
```cpp
sizeof(sys_sem_t*) == sizeof(sys_sem_t) == sizeof(void*)
```

But it's incorrect and should be fixed, thanks for noticing!

**Comment by david-cermak** [comment]
Fixed in https://github.com/espressif/esp-lwip/commit/d6b006094bd1cdaa3890da175a9548432f2028a9
