### ISSUE TITLE
ip4_forward return? (IDFGH-9883)

### ISSUE THREAD

**Issue by briliant-ben** [espressif/esp-lwip#55]
https://github.com/espressif/esp-lwip/blob/d5e56d06658ae11292be1baea56204f7120b6fa7/src/core/ipv4/ip4.c#L661

If ip_forward successfully forwards the pbuf, then why not consider going straight back without the need for further steps? I am confused, please enlighten!

**Comment by david-cermak** [comment]
after calling the `ip4_forward()` (no matter if successfully or not) we are going straight back, are we not?

https://github.com/espressif/esp-lwip/blob/d5e56d06658ae11292be1baea56204f7120b6fa7/src/core/ipv4/ip4.c#L669-L670

which *further steps* you mean? The latter call of `pbuf_free()` or checking/adding an error code to the function?

**Comment by briliant-ben** [comment]
You are right, I see. I missed close brace here, thanks for explanation!
