### ISSUE TITLE
ip_napt fixes and improvements should be forward-ported from 2.1.2 to 2.1.3 (IDFGH-10206)

### ISSUE THREAD

**Issue by rojer** [espressif/esp-lwip#56]
Histories for ip4_napt.c have significantly diverged: [2.1.2](https://github.com/espressif/esp-lwip/commits/2.1.2-esp/src/core/ipv4/ip4_napt.c) vs [2.1.3](https://github.com/espressif/esp-lwip/commits/2.1.3-esp/src/core/ipv4/ip4_napt.c).
A number of changes made to 2.1.2 need to be forward-ported to 2.1.3

**Comment by david-cermak** [comment]
Changes have been forward ported in fadb91094667e5623da91572c47c4fdc73a4f6ee
